#!/usr/bin/env node
/**
 * Generates supabase/seed.sql from the TypeScript mock data in data/mockData/.
 *
 *   node scripts/generate-seed.mjs
 *
 * The mock data is the single source of truth for the demo dataset, so the
 * database seed is derived from it rather than maintained by hand.
 */
import { build } from 'esbuild';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// --- 1. Bundle the mock data so Node can import it (enums are not erasable) ---
const tmp = await mkdtemp(join(tmpdir(), 'koriq-seed-'));
const bundle = join(tmp, 'mock.mjs');
await build({
    entryPoints: [join(root, 'data/mockData/index.ts')],
    bundle: true,
    platform: 'node',
    format: 'esm',
    outfile: bundle,
    logLevel: 'silent',
});
const mock = await import(pathToFileURL(bundle).href);
await rm(tmp, { recursive: true, force: true });

// --- 2. SQL helpers ---
const q = (v) => {
    if (v === null || v === undefined) return 'null';
    if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'null';
    if (typeof v === 'boolean') return v ? 'true' : 'false';
    return `'${String(v).replace(/'/g, "''")}'`;
};
const jsonb = (v) => `${q(JSON.stringify(v ?? {}))}::jsonb`;
const dateOnly = (iso) => (iso ? q(String(iso).slice(0, 10)) : 'current_date');
const row = (vals) => `    (${vals.join(', ')})`;

const out = [];
const emit = (s = '') => out.push(s);

emit('-- ============================================================================');
emit('-- KorIQ demo seed — GENERATED by scripts/generate-seed.mjs from data/mockData/.');
emit('-- Do not edit by hand; edit the mock data and re-run the script.');
emit('-- Safe to re-run: every statement is idempotent.');
emit('-- ============================================================================');
emit();

// --- 3. Clubs ---
emit('insert into public.clubs (id, name, location, website_url) values');
emit(mock.MOCK_CLUBS.map((c) => row([q(c.id), q(c.name), q(c.location ?? null), q(c.websiteUrl ?? null)])).join(',\n'));
emit('on conflict (id) do update set name = excluded.name, location = excluded.location;');
emit();

// --- 4. Coaches ---
emit('insert into public.coaches (id, name, email, phone, club_id, coach_type, status, joined_date, rate, specialties, bio, rating, review_count) values');
emit(
    mock.MOCK_COACHES.map((c) =>
        row([
            q(c.id), q(c.name), q(c.email), q(c.phone ?? null), q(c.clubId ?? null), q(c.coachType), q(c.status),
            dateOnly(c.joinedDate), q(c.rate ?? null),
            c.specialties?.length ? `array[${c.specialties.map(q).join(', ')}]::text[]` : 'null',
            q(c.bio ?? null), q(c.rating ?? null), q(c.reviewCount ?? null),
        ])
    ).join(',\n')
);
emit('on conflict (id) do update set name = excluded.name, email = excluded.email, club_id = excluded.club_id, coach_type = excluded.coach_type, status = excluded.status;');
emit();

// --- 5. Students ---
emit('insert into public.students (id, name, email, age, current_ntrp, starting_ntrp, club_id, primary_coach_id, status, joined_date, created_from, physical_attributes, total_paid, last_payment_date, payment_count) values');
emit(
    mock.MOCK_STUDENTS.map((s) =>
        row([
            q(s.id), q(s.name), q(s.email), q(s.age), q(s.currentNtrp), q(s.startingNtrp ?? null),
            q(s.clubId ?? null), q(s.primaryCoachId ?? null), q(s.status), dateOnly(s.joinedDate),
            q(s.createdFrom ?? null), s.physicalAttributes ? jsonb(s.physicalAttributes) : 'null',
            q(s.totalPaid ?? null), s.lastPaymentDate ? dateOnly(s.lastPaymentDate) : 'null', q(s.paymentCount ?? null),
        ])
    ).join(',\n')
);
emit('on conflict (id) do update set name = excluded.name, email = excluded.email, age = excluded.age, current_ntrp = excluded.current_ntrp, starting_ntrp = excluded.starting_ntrp, club_id = excluded.club_id, primary_coach_id = excluded.primary_coach_id, status = excluded.status;');
emit();

// --- 6. Players ---
emit('insert into public.players (id, name, email, city, current_ntrp, joined_date, extras) values');
emit(
    mock.MOCK_PLAYERS.map((p) => {
        const { id, name, email, city, currentNtrp, joinedDate, ...extras } = p;
        return row([q(id), q(name), q(email), q(city), q(currentNtrp), dateOnly(joinedDate), jsonb(extras)]);
    }).join(',\n')
);
emit('on conflict (id) do update set name = excluded.name, email = excluded.email, city = excluded.city, current_ntrp = excluded.current_ntrp;');
emit();

// --- 7. Evaluations: legacy "sessions" + newer rotation-style evaluations ---
const evalRows = [];

for (const s of mock.MOCK_SESSIONS) {
    evalRows.push([
        q(s.id), q(s.studentId), q(s.coachId), q(s.clubId ?? null), q(s.date), q(s.ntrpLevel),
        q(s.classType), q(s.sessionType), q(s.durationMinutes),
        q(s.fundamentals.fhScore), q(s.fundamentals.bhScore), q(s.fundamentals.serveScore), q(s.fundamentals.volleyScore),
        jsonb(s.performance.scores), q(s.notes ?? ''),
    ]);
}

for (const e of mock.MOCK_EVALUATIONS ?? []) {
    const f = e.fundamentals ?? {};
    evalRows.push([
        q(e.id), q(e.studentId), q(e.evaluatingCoachId), q(e.clubId ?? null), q(e.date), q(e.ntrpLevel),
        q(e.classType), q(e.sessionType), q(e.durationMinutes),
        q(f.forehand?.average ?? 0), q(f.backhand?.average ?? 0), q(f.serve?.average ?? 0), q(f.volley?.average ?? 0),
        jsonb(e.performance?.scores), q(e.notes ?? ''),
    ]);
}

emit('-- Scores (averages, weighted final) are recomputed by trigger on insert.');
emit('insert into public.evaluations (id, student_id, coach_id, club_id, evaluated_at, ntrp_level, class_type, session_type, duration_minutes, fh_score, bh_score, serve_score, volley_score, performance_scores, notes) values');
emit(evalRows.map(row).join(',\n'));
emit('on conflict (id) do nothing;');
emit();

// --- 8. Demo auth users + profiles ---
// Mock usernames become <username>@koriq.demo; the login form maps bare
// usernames to that domain so the README demo accounts keep working.
const DEMO_DOMAIN = 'koriq.demo';
emit('-- Demo accounts (password: "password"). Inserted directly into auth so the');
emit('-- seed is reproducible without the service-role key.');
emit('do $$');
emit('declare');
emit('    v_uid uuid;');
emit('begin');
for (const u of mock.MOCK_USERS) {
    const email = `${u.username}@${DEMO_DOMAIN}`;
    emit(`    -- ${u.role}: ${email} -> ${u.linkedEntityId}`);
    emit(`    select id into v_uid from auth.users where email = ${q(email)};`);
    emit('    if v_uid is null then');
    emit('        v_uid := gen_random_uuid();');
    emit('        insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,');
    emit('                                raw_app_meta_data, raw_user_meta_data, created_at, updated_at,');
    emit('                                confirmation_token, recovery_token, email_change_token_new, email_change)');
    emit(`        values ('00000000-0000-0000-0000-000000000000', v_uid, 'authenticated', 'authenticated', ${q(email)},`);
    emit(`                crypt(${q(u.password)}, gen_salt('bf')), now(),`);
    emit(`                '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(), '', '', '', '');`);
    emit('        insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)');
    emit(`        values (gen_random_uuid(), v_uid, v_uid::text,`);
    emit(`                jsonb_build_object('sub', v_uid::text, 'email', ${q(email)}, 'email_verified', true),`);
    emit(`                'email', now(), now(), now());`);
    emit('    else');
    emit('        -- Re-seeding always restores the demo password, in case a visitor changed it.');
    emit(`        update auth.users set encrypted_password = crypt(${q(u.password)}, gen_salt('bf')), updated_at = now() where id = v_uid;`);
    emit('    end if;');
    emit('    insert into public.profiles (user_id, role, linked_entity_id, email, onboarding_completed_at)');
    emit(`    values (v_uid, ${q(u.role)}, ${q(u.linkedEntityId)}, ${q(email)}, now())`);
    emit('    on conflict (user_id, role) do update set linked_entity_id = excluded.linked_entity_id;');
    emit();
}
emit('end $$;');
emit();

const target = join(root, 'supabase/seed.sql');
await writeFile(target, out.join('\n'));
console.log(
    `Wrote ${target}: ${mock.MOCK_CLUBS.length} clubs, ${mock.MOCK_COACHES.length} coaches, ` +
    `${mock.MOCK_STUDENTS.length} students, ${mock.MOCK_PLAYERS.length} players, ` +
    `${evalRows.length} evaluations, ${mock.MOCK_USERS.length} demo users`
);
