-- ============================================================================
-- KorIQ demo seed — GENERATED by scripts/generate-seed.mjs from data/mockData/.
-- Do not edit by hand; edit the mock data and re-run the script.
-- Safe to re-run: every statement is idempotent.
-- ============================================================================

insert into public.clubs (id, name, location, website_url) values
    ('club_vancouver', 'Vancouver Tennis Club', 'Vancouver, BC', null),
    ('club_richmond', 'Richmond Racquet Club', 'Richmond, BC', null),
    ('club_burnaby', 'Burnaby Tennis Academy', 'Burnaby, BC', null)
on conflict (id) do update set name = excluded.name, location = excluded.location;

insert into public.coaches (id, name, email, phone, club_id, coach_type, status, joined_date, rate, specialties, bio, rating, review_count) values
    ('c1', 'Coach Mike', 'mike@club.com', null, 'club_vancouver', 'Club', 'Active', '2023-01-15', null, null, null, 4.8, null),
    ('c2', 'Coach Sarah', 'sarah@club.com', null, 'club_vancouver', 'Club', 'Active', '2023-02-20', null, null, null, 4.6, null),
    ('c3', 'Coach Tom', 'tom@independent.com', null, 'club_vancouver', 'Independent', 'Active', '2023-05-10', null, null, null, 4.5, null),
    ('c4', 'Coach Jessica', 'jessica@club.com', null, 'club_vancouver', 'Both', 'Active', '2023-06-01', null, null, null, 4.7, null),
    ('c5', 'Coach Alex', 'alex@club.com', null, 'club_vancouver', 'Club', 'Active', '2023-09-01', null, null, null, 4.4, null)
on conflict (id) do update set name = excluded.name, email = excluded.email, club_id = excluded.club_id, coach_type = excluded.coach_type, status = excluded.status;

insert into public.students (id, name, email, age, current_ntrp, starting_ntrp, club_id, primary_coach_id, status, joined_date, created_from, physical_attributes, total_paid, last_payment_date, payment_count) values
    ('s1', 'Olivia Tennis', 'olivia@example.com', 14, '3.5', '3.0', 'club_vancouver', 'c1', 'Claimed', '2024-01-10', null, null, null, null, null),
    ('s2', 'James Racket', 'james@example.com', 10, '2.0-2.5', '1.0-1.5', 'club_vancouver', 'c2', 'Claimed', '2024-02-15', null, null, null, null, null),
    ('s3', 'Emma Chen', 'emma@example.com', 12, '2.0-2.5', '2.0-2.5', 'club_vancouver', 'c1', 'Claimed', '2024-03-01', null, null, null, null, null),
    ('s4', 'Jake Wilson', 'jake@example.com', 16, '3.0', '2.0-2.5', 'club_vancouver', 'c2', 'Unclaimed', '2024-06-20', null, null, null, null, null),
    ('s5', 'Sofia Martinez', 'sofia@example.com', 8, '1.0-1.5', '1.0-1.5', 'club_vancouver', 'c3', 'Claimed', '2024-07-10', null, null, null, null, null),
    ('s6', 'Lucas Brown', 'lucas@example.com', 15, '4.0', '3.5', 'club_vancouver', 'c4', 'Unclaimed', '2024-08-05', null, null, null, null, null),
    ('s7', 'Ava Johnson', 'ava@example.com', 11, '3.0', '2.0-2.5', 'club_vancouver', 'c2', 'Claimed', '2024-09-12', null, null, null, null, null),
    ('s8', 'Ethan Lee', 'ethan@example.com', 13, '3.5', '3.0', 'club_vancouver', 'c1', 'Claimed', '2024-10-01', null, null, null, null, null),
    ('s9', 'Mia Davis', 'mia@example.com', 9, '2.0-2.5', '1.0-1.5', 'club_vancouver', 'c3', 'Claimed', '2024-11-15', null, null, null, null, null),
    ('s10', 'Noah Miller', 'noah@example.com', 17, '4.5', '4.0', 'club_vancouver', 'c5', 'Unclaimed', '2024-12-05', null, null, null, null, null),
    ('s11', 'Isabella Taylor', 'isa@example.com', 14, '3.5', '3.5', 'club_vancouver', 'c4', 'Claimed', '2025-01-05', null, null, null, null, null)
on conflict (id) do update set name = excluded.name, email = excluded.email, age = excluded.age, current_ntrp = excluded.current_ntrp, starting_ntrp = excluded.starting_ntrp, club_id = excluded.club_id, primary_coach_id = excluded.primary_coach_id, status = excluded.status;

insert into public.players (id, name, email, city, current_ntrp, joined_date, extras) values
    ('p1', 'Pro Player', 'player@example.com', 'Vancouver', '4.5', '2024-01-01', '{}'::jsonb),
    ('p2', 'Weekend Warrior', 'weekend@example.com', 'Burnaby', '3.5', '2024-03-15', '{}'::jsonb),
    ('p3', 'Tennis Newbie', 'newbie@example.com', 'Richmond', '2.0-2.5', '2024-06-01', '{}'::jsonb)
on conflict (id) do update set name = excluded.name, email = excluded.email, city = excluded.city, current_ntrp = excluded.current_ntrp;

-- Scores (averages, weighted final) are recomputed by trigger on insert.
insert into public.evaluations (id, student_id, coach_id, club_id, evaluated_at, ntrp_level, class_type, session_type, duration_minutes, fh_score, bh_score, serve_score, volley_score, performance_scores, notes) values
    ('sess1', 's1', 'c1', null, '2024-02-15', '3.0', '1-on-1', 'CLUB', 60, 6.5, 5.8, 6, 5.5, '{"consistency":6.2,"shotSelection":5.8,"movement":6}'::jsonb, 'Good baseline. Needs work on backhand.'),
    ('sess2', 's1', 'c1', null, '2024-03-20', '3.0', '1-on-1', 'CLUB', 60, 7, 6.2, 6.5, 5.8, '{"consistency":6.8,"shotSelection":6.2,"movement":6.5}'::jsonb, 'Forehand improving nicely.'),
    ('sess3', 's1', 'c2', null, '2024-04-10', '3.0', '1-on-1', 'CLUB', 60, 6.8, 6, 6.2, 5.5, '{"consistency":6.5,"shotSelection":6,"movement":6.2}'::jsonb, 'Worked on volley technique.'),
    ('sess4', 's1', 'c1', null, '2024-05-15', '3.0', '1-on-1', 'CLUB', 60, 7.5, 7, 7.2, 6.5, '{"consistency":7.5,"shotSelection":7,"movement":7.2}'::jsonb, 'Great progress! Consistency is solid.'),
    ('sess5', 's1', 'c1', null, '2024-06-20', '3.0', '1-on-1', 'CLUB', 60, 8, 7.5, 7.8, 7, '{"consistency":8.2,"shotSelection":7.8,"movement":8}'::jsonb, 'Ready for level up! Unlocking 3.5.'),
    ('sess6', 's1', 'c1', null, '2024-08-10', '3.5', '1-on-1', 'CLUB', 60, 6, 5.5, 5.8, 5, '{"consistency":5.5,"shotSelection":5.2,"movement":5.5}'::jsonb, 'First session at 3.5. Adjusting to new standards.'),
    ('sess7', 's1', 'c2', null, '2024-09-15', '3.5', '1-on-1', 'CLUB', 60, 6.2, 5.8, 6, 5.2, '{"consistency":5.8,"shotSelection":5.5,"movement":5.8}'::jsonb, 'Building at new level.'),
    ('sess8', 's1', 'c1', null, '2024-11-01', '3.5', '1-on-1', 'CLUB', 60, 6.8, 6.2, 6.5, 5.8, '{"consistency":6.5,"shotSelection":6.2,"movement":6.5}'::jsonb, 'Good adaptation to 3.5 level.'),
    ('sess9', 's2', 'c2', null, '2024-03-01', '1.0-1.5', '1-on-1', 'CLUB', 60, 5.5, 4.8, 5, 4.5, '{"basicRally":5.8,"courtCoverage":5.2}'::jsonb, 'Young beginner. Enthusiastic!'),
    ('sess10', 's2', 'c2', null, '2024-04-15', '1.0-1.5', '1-on-1', 'CLUB', 60, 6.5, 5.5, 6, 5, '{"basicRally":6.8,"courtCoverage":6.2}'::jsonb, 'Good grip on fundamentals now.'),
    ('sess11', 's2', 'c2', null, '2024-06-01', '1.0-1.5', '1-on-1', 'CLUB', 60, 7.5, 6.8, 7, 6, '{"basicRally":7.8,"courtCoverage":7.2}'::jsonb, 'Almost ready for 2.0-2.5!'),
    ('sess12', 's2', 'c2', null, '2024-07-15', '1.0-1.5', '1-on-1', 'CLUB', 60, 8.2, 7.5, 7.8, 7, '{"basicRally":8.5,"courtCoverage":8}'::jsonb, 'Level up! Moving to 2.0-2.5.'),
    ('sess13', 's2', 'c2', null, '2024-09-01', '2.0-2.5', '1-on-1', 'CLUB', 60, 5.5, 5, 5.2, 4.8, '{"consistency":5.2,"shotSelection":4.8,"movement":5}'::jsonb, 'Starting at new level.'),
    ('sess14', 's2', 'c2', null, '2024-11-15', '2.0-2.5', '1-on-1', 'CLUB', 60, 6.2, 5.8, 6, 5.5, '{"consistency":6.2,"shotSelection":5.8,"movement":6}'::jsonb, 'Progressing well at 2.0-2.5.'),
    ('sess15', 's8', 'c1', null, '2024-10-15', '3.0', '1-on-1', 'CLUB', 60, 7.2, 6.8, 7, 6.5, '{"consistency":7,"shotSelection":6.8,"movement":7}'::jsonb, 'Strong baseline player.'),
    ('sess16', 's8', 'c4', null, '2024-11-01', '3.0', '1-on-1', 'CLUB', 60, 7, 7.2, 7, 6.8, '{"consistency":7.2,"shotSelection":7,"movement":7.2}'::jsonb, 'Nice backhand. Focus on net game.'),
    ('sess17', 's8', 'c1', null, '2024-12-01', '3.0', '1-on-1', 'CLUB', 60, 8, 7.8, 7.8, 7.2, '{"consistency":8,"shotSelection":7.8,"movement":8}'::jsonb, 'Ready for 3.5!'),
    ('sess18', 's8', 'c1', null, '2025-01-15', '3.5', '1-on-1', 'CLUB', 60, 6, 5.8, 5.8, 5.5, '{"consistency":5.8,"shotSelection":5.5,"movement":5.8}'::jsonb, 'First evaluation at 3.5.'),
    ('sess19', 's10', 'c5', null, '2024-12-10', '4.0', '1-on-1', 'CLUB', 60, 7.8, 7.5, 7.8, 7.2, '{"tacticalPlay":7.5,"powerControl":7.2,"mentalGame":7}'::jsonb, 'Advanced player. Good court sense.'),
    ('sess20', 's10', 'c5', null, '2025-01-05', '4.0', '1-on-1', 'CLUB', 60, 8.2, 8, 8.2, 7.8, '{"tacticalPlay":8.2,"powerControl":8,"mentalGame":7.8}'::jsonb, 'Outstanding progress. 4.5 material.'),
    ('sess21', 's9', 'c3', null, '2024-11-20', '1.0-1.5', '1-on-1', 'CLUB', 60, 7, 6.5, 6.8, 6.2, '{"basicRally":7.2,"courtCoverage":6.8}'::jsonb, 'Quick learner!'),
    ('sess22', 's9', 'c3', null, '2024-12-15', '1.0-1.5', '1-on-1', 'CLUB', 60, 8, 7.5, 7.8, 7, '{"basicRally":8.2,"courtCoverage":7.8}'::jsonb, 'Level up to 2.0-2.5!'),
    ('sess23', 's9', 'c3', null, '2025-01-10', '2.0-2.5', '1-on-1', 'CLUB', 60, 5.8, 5.2, 5.5, 5, '{"consistency":5.5,"shotSelection":5.2,"movement":5.5}'::jsonb, 'Starting at new level. Good attitude.'),
    ('sess24', 's7', 'c2', null, '2024-09-20', '2.0-2.5', '1-on-1', 'CLUB', 60, 6.8, 6.2, 6.5, 6, '{"consistency":6.8,"shotSelection":6.2,"movement":6.5}'::jsonb, 'Good fundamentals.'),
    ('sess25', 's7', 'c1', null, '2024-10-20', '2.0-2.5', '1-on-1', 'CLUB', 60, 7.2, 6.8, 7, 6.5, '{"consistency":7.2,"shotSelection":6.8,"movement":7}'::jsonb, 'Nice improvement on serve.'),
    ('sess26', 's7', 'c2', null, '2024-11-20', '2.0-2.5', '1-on-1', 'CLUB', 60, 8, 7.5, 7.8, 7.2, '{"consistency":8,"shotSelection":7.5,"movement":7.8}'::jsonb, 'Ready for 3.0!'),
    ('sess27', 's7', 'c2', null, '2025-01-05', '3.0', '1-on-1', 'CLUB', 60, 5.5, 5, 5.2, 4.8, '{"consistency":5.2,"shotSelection":5,"movement":5.2}'::jsonb, 'First session at 3.0. Building up.'),
    ('eval-001', 's3', 'c1', 'club_vancouver', '2025-09-09T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 5, 0, 0, 0, '{"Ball Judgment":5,"Rally Ability":4,"Movement":5,"Recovery":4,"Stroke Development":5,"Court Positions":4}'::jsonb, 'First session. Emma has a solid eastern grip but needs work on follow-through.'),
    ('eval-002', 's3', 'c1', 'club_vancouver', '2025-09-16T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 0, 4.4, 0, 0, '{"Ball Judgment":5,"Rally Ability":5,"Movement":5,"Recovery":5,"Stroke Development":5,"Court Positions":4}'::jsonb, 'Backhand needs two-hand consistency. Good court awareness improving.'),
    ('eval-003', 's3', 'c1', 'club_vancouver', '2025-09-23T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 0, 0, 0, 4, '{"Ball Judgment":5,"Rally Ability":5,"Movement":5,"Recovery":5,"Stroke Development":5,"Court Positions":5}'::jsonb, 'Net game is weakest area. Needs to keep racket face stable on volleys.'),
    ('eval-004', 's3', 'c1', 'club_vancouver', '2025-09-30T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 0, 0, 5, 0, '{"Ball Judgment":6,"Rally Ability":5,"Movement":6,"Recovery":5,"Stroke Development":6,"Court Positions":5}'::jsonb, 'Good progress on continental grip for serve. Toss consistency improving.'),
    ('eval-005', 's3', 'c1', 'club_vancouver', '2025-10-07T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 5.8, 5.2, 0, 0, '{"Ball Judgment":6,"Rally Ability":6,"Movement":6,"Recovery":5,"Stroke Development":6,"Court Positions":5}'::jsonb, 'Groundstrokes becoming more reliable. Starting to direct the ball.'),
    ('eval-006', 's3', 'c1', 'club_vancouver', '2025-10-14T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 6.2, 5.4, 5.4, 4.8, '{"Ball Judgment":6,"Rally Ability":6,"Movement":6,"Recovery":6,"Stroke Development":6,"Court Positions":6}'::jsonb, 'Mid-term assessment. All strokes evaluated. Good all-round improvement.'),
    ('eval-007', 's3', 'c1', 'club_vancouver', '2026-01-13T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 6.6, 0, 0, 0, '{"Ball Judgment":7,"Rally Ability":6,"Movement":6,"Recovery":6,"Stroke Development":7,"Court Positions":6}'::jsonb, 'Forehand has improved notably since fall. Good lateral movement.'),
    ('eval-008', 's3', 'c1', 'club_vancouver', '2026-02-10T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 0, 0, 6.2, 0, '{"Ball Judgment":7,"Rally Ability":7,"Movement":7,"Recovery":6,"Stroke Development":7,"Court Positions":6}'::jsonb, 'Serve is getting more consistent. Working on second serve placement.'),
    ('eval-009', 's7', 'c1', 'club_vancouver', '2025-09-09T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 5.6, 0, 0, 0, '{"Ball Judgment":6,"Rally Ability":5,"Movement":6,"Recovery":5,"Stroke Development":6,"Court Positions":5}'::jsonb, 'Ava has strong fundamentals for her age. Good natural swing path.'),
    ('eval-010', 's7', 'c1', 'club_vancouver', '2025-09-16T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 0, 5.2, 0, 0, '{"Ball Judgment":6,"Rally Ability":6,"Movement":6,"Recovery":5,"Stroke Development":6,"Court Positions":5}'::jsonb, 'Two-handed backhand is developing well. Good footwork getting into position.'),
    ('eval-011', 's7', 'c1', 'club_vancouver', '2025-10-14T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 6.6, 5.8, 5.4, 5, '{"Ball Judgment":7,"Rally Ability":6,"Movement":7,"Recovery":6,"Stroke Development":7,"Court Positions":6}'::jsonb, 'Strong mid-term showing. Ava is one of the most improved students this term.'),
    ('eval-012', 's1', 'c4', 'club_vancouver', '2025-09-10T20:00:00Z', '3.5', 'Group', 'CLUB', 90, 7.2, 0, 0, 0, '{"Stroke Dependability":7,"Depth":6,"Variety":6,"Lobs/Overheads":5,"Approach Shots":6,"Volleys":6,"Net Comfort":6}'::jsonb, 'Olivia is an advanced student with excellent forehand. Focus on approach shots.'),
    ('eval-013', 's1', 'c4', 'club_vancouver', '2025-09-17T20:00:00Z', '3.5', 'Group', 'CLUB', 90, 0, 6.8, 0, 0, '{"Stroke Dependability":7,"Depth":7,"Variety":6,"Lobs/Overheads":6,"Approach Shots":6,"Volleys":6,"Net Comfort":6}'::jsonb, 'Backhand is solid but could use more depth. Working on drive vs slice choices.'),
    ('eval-014', 's1', 'c4', 'club_vancouver', '2025-10-15T20:00:00Z', '3.5', 'Group', 'CLUB', 90, 7.4, 7, 7, 6.2, '{"Stroke Dependability":8,"Depth":7,"Variety":7,"Lobs/Overheads":6,"Approach Shots":7,"Volleys":7,"Net Comfort":7}'::jsonb, 'End-of-term comprehensive assessment. Olivia is progressing toward 4.0 readiness.'),
    ('eval-015', 's1', 'c4', 'club_vancouver', '2026-03-25T20:00:00Z', '3.5', 'Group', 'CLUB', 90, 7.6, 0, 0, 0, '{"Stroke Dependability":8,"Depth":7,"Variety":7,"Lobs/Overheads":7,"Approach Shots":7,"Volleys":7,"Net Comfort":7}'::jsonb, 'Good start to spring term. Forehand is weapon-grade at this level.'),
    ('eval-016', 's4', 'c1', 'club_vancouver', '2025-09-09T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 5.4, 0, 0, 0, '{"Ball Judgment":5,"Rally Ability":5,"Movement":6,"Recovery":5,"Stroke Development":5,"Court Positions":5}'::jsonb, 'Jake is athletic with good movement. Needs technical refinement.'),
    ('eval-017', 's4', 'c1', 'club_vancouver', '2025-10-14T19:00:00Z', '2.0-2.5', 'Group', 'CLUB', 90, 6.4, 5.6, 5.8, 5.2, '{"Ball Judgment":7,"Rally Ability":6,"Movement":7,"Recovery":6,"Stroke Development":7,"Court Positions":6}'::jsonb, 'Big improvement this term. Jake is ready for 3.0 level work next term.'),
    ('eval-018', 's5', 'c3', 'club_vancouver', '2025-09-13T09:00:00Z', '1.0-1.5', 'Group', 'CLUB', 90, 3.2, 0, 0, 0, '{"Ball Contact":4,"Racket Control":3,"Ball in Play":3,"Stroke Attempts":5,"Serve Attempt":2}'::jsonb, 'Sofia is brand new to tennis. Great enthusiasm! Working on just making contact.'),
    ('eval-019', 's5', 'c3', 'club_vancouver', '2025-11-01T09:00:00Z', '1.0-1.5', 'Group', 'CLUB', 90, 4.6, 3.4, 3.2, 3.2, '{"Ball Contact":6,"Racket Control":5,"Ball in Play":5,"Stroke Attempts":6,"Serve Attempt":4}'::jsonb, 'Huge improvement for Sofia. Consistent forehand rallies now. Ready on schedule.'),
    ('eval-020', 's8', 'c4', 'club_vancouver', '2025-09-10T20:00:00Z', '3.5', 'Group', 'CLUB', 90, 6.4, 0, 0, 0, '{"Stroke Dependability":6,"Depth":6,"Variety":5,"Lobs/Overheads":5,"Approach Shots":5,"Volleys":5,"Net Comfort":5}'::jsonb, 'Ethan just moved up to 3.5. Finding the level challenging but committed.'),
    ('eval-021', 's8', 'c4', 'club_vancouver', '2025-10-15T20:00:00Z', '3.5', 'Group', 'CLUB', 90, 6.8, 6.2, 6.2, 5.4, '{"Stroke Dependability":7,"Depth":6,"Variety":6,"Lobs/Overheads":5,"Approach Shots":6,"Volleys":6,"Net Comfort":6}'::jsonb, 'Adapting well to this level. Needs more work on approach shot transitions.')
on conflict (id) do nothing;

-- Demo accounts (password: "password"). Inserted directly into auth so the
-- seed is reproducible without the service-role key.
do $$
declare
    v_uid uuid;
begin
    -- COACH: coach@koriq.demo -> c1
    select id into v_uid from auth.users where email = 'coach@koriq.demo';
    if v_uid is null then
        v_uid := gen_random_uuid();
        insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                                raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                                confirmation_token, recovery_token, email_change_token_new, email_change)
        values ('00000000-0000-0000-0000-000000000000', v_uid, 'authenticated', 'authenticated', 'coach@koriq.demo',
                crypt('password', gen_salt('bf')), now(),
                '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(), '', '', '', '');
        insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
        values (gen_random_uuid(), v_uid, v_uid::text,
                jsonb_build_object('sub', v_uid::text, 'email', 'coach@koriq.demo', 'email_verified', true),
                'email', now(), now(), now());
    else
        -- Re-seeding always restores the demo password, in case a visitor changed it.
        update auth.users set encrypted_password = crypt('password', gen_salt('bf')), updated_at = now() where id = v_uid;
    end if;
    insert into public.profiles (user_id, role, linked_entity_id, email, onboarding_completed_at)
    values (v_uid, 'COACH', 'c1', 'coach@koriq.demo', now())
    on conflict (user_id, role) do update set linked_entity_id = excluded.linked_entity_id;

    -- COACH: coach2@koriq.demo -> c2
    select id into v_uid from auth.users where email = 'coach2@koriq.demo';
    if v_uid is null then
        v_uid := gen_random_uuid();
        insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                                raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                                confirmation_token, recovery_token, email_change_token_new, email_change)
        values ('00000000-0000-0000-0000-000000000000', v_uid, 'authenticated', 'authenticated', 'coach2@koriq.demo',
                crypt('password', gen_salt('bf')), now(),
                '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(), '', '', '', '');
        insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
        values (gen_random_uuid(), v_uid, v_uid::text,
                jsonb_build_object('sub', v_uid::text, 'email', 'coach2@koriq.demo', 'email_verified', true),
                'email', now(), now(), now());
    else
        -- Re-seeding always restores the demo password, in case a visitor changed it.
        update auth.users set encrypted_password = crypt('password', gen_salt('bf')), updated_at = now() where id = v_uid;
    end if;
    insert into public.profiles (user_id, role, linked_entity_id, email, onboarding_completed_at)
    values (v_uid, 'COACH', 'c2', 'coach2@koriq.demo', now())
    on conflict (user_id, role) do update set linked_entity_id = excluded.linked_entity_id;

    -- STUDENT: student@koriq.demo -> s1
    select id into v_uid from auth.users where email = 'student@koriq.demo';
    if v_uid is null then
        v_uid := gen_random_uuid();
        insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                                raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                                confirmation_token, recovery_token, email_change_token_new, email_change)
        values ('00000000-0000-0000-0000-000000000000', v_uid, 'authenticated', 'authenticated', 'student@koriq.demo',
                crypt('password', gen_salt('bf')), now(),
                '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(), '', '', '', '');
        insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
        values (gen_random_uuid(), v_uid, v_uid::text,
                jsonb_build_object('sub', v_uid::text, 'email', 'student@koriq.demo', 'email_verified', true),
                'email', now(), now(), now());
    else
        -- Re-seeding always restores the demo password, in case a visitor changed it.
        update auth.users set encrypted_password = crypt('password', gen_salt('bf')), updated_at = now() where id = v_uid;
    end if;
    insert into public.profiles (user_id, role, linked_entity_id, email, onboarding_completed_at)
    values (v_uid, 'STUDENT', 's1', 'student@koriq.demo', now())
    on conflict (user_id, role) do update set linked_entity_id = excluded.linked_entity_id;

    -- CLUB: club@koriq.demo -> club_vancouver
    select id into v_uid from auth.users where email = 'club@koriq.demo';
    if v_uid is null then
        v_uid := gen_random_uuid();
        insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                                raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                                confirmation_token, recovery_token, email_change_token_new, email_change)
        values ('00000000-0000-0000-0000-000000000000', v_uid, 'authenticated', 'authenticated', 'club@koriq.demo',
                crypt('password', gen_salt('bf')), now(),
                '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(), '', '', '', '');
        insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
        values (gen_random_uuid(), v_uid, v_uid::text,
                jsonb_build_object('sub', v_uid::text, 'email', 'club@koriq.demo', 'email_verified', true),
                'email', now(), now(), now());
    else
        -- Re-seeding always restores the demo password, in case a visitor changed it.
        update auth.users set encrypted_password = crypt('password', gen_salt('bf')), updated_at = now() where id = v_uid;
    end if;
    insert into public.profiles (user_id, role, linked_entity_id, email, onboarding_completed_at)
    values (v_uid, 'CLUB', 'club_vancouver', 'club@koriq.demo', now())
    on conflict (user_id, role) do update set linked_entity_id = excluded.linked_entity_id;

    -- PLAYER: player@koriq.demo -> p1
    select id into v_uid from auth.users where email = 'player@koriq.demo';
    if v_uid is null then
        v_uid := gen_random_uuid();
        insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                                raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                                confirmation_token, recovery_token, email_change_token_new, email_change)
        values ('00000000-0000-0000-0000-000000000000', v_uid, 'authenticated', 'authenticated', 'player@koriq.demo',
                crypt('password', gen_salt('bf')), now(),
                '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb, now(), now(), '', '', '', '');
        insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
        values (gen_random_uuid(), v_uid, v_uid::text,
                jsonb_build_object('sub', v_uid::text, 'email', 'player@koriq.demo', 'email_verified', true),
                'email', now(), now(), now());
    else
        -- Re-seeding always restores the demo password, in case a visitor changed it.
        update auth.users set encrypted_password = crypt('password', gen_salt('bf')), updated_at = now() where id = v_uid;
    end if;
    insert into public.profiles (user_id, role, linked_entity_id, email, onboarding_completed_at)
    values (v_uid, 'PLAYER', 'p1', 'player@koriq.demo', now())
    on conflict (user_id, role) do update set linked_entity_id = excluded.linked_entity_id;

end $$;
